### ISSUE TITLE
Spinnaker Pod Annotation Support

### ISSUE THREAD

**Issue by cablespaghetti** [armory/spinnaker-operator#138]
In the documentation it mentions kube2iam a few times, but there is no way I can see to add the necessary annotations to the spinnaker pods to make this work. It would be much appreciated if this could be added to the operator.

Thanks

**Comment by ncknt** [comment]
Hi @cablespaghetti , you should be able to add these annotations either via:
- `spec.spinnakerConfig.service-settings.gate.kubernetes.podAnnotations` (https://spinnaker.io/reference/halyard/custom/#kubernetes)
- or with a `spec.kustomize.gate.deployment`(and add a kustomization patch to the deployment: https://github.com/armory/spinnaker-operator/blob/master/doc/options.md#kustomize-examples
