### ISSUE TITLE
Google Cloud Pub/Sub

### ISSUE THREAD

**Issue by andrijaperovic** [armory/spinnaker-operator#167]
Currently evaluating Spinnaker operator for migrating some existing Spinnaker pipelines which we have running in our development and production environments.

I see that the `spinnakerservice.yaml` in spinnaker-kustomize-patches includes a `pubsub` section for integration with pubsub providers, is there any working example of a `SpinnakerService` configuration with Google Cloud Pub/Sub in mind?

**Comment by ncknt** [comment]
There's no example currently but the format of `pubsub` is explained here: https://docs.armory.io/docs/installation/operator-reference/pubsub/

We welcome contributions if you want to submit a PR to the `spinnaker-kustomize-patch` :)

**Comment by andrijaperovic** [comment]
Perfect, thank you @ncknt ! Will look into submitting a PR when we have a working configuration.

**Comment by andrijaperovic** [comment]
@ncknt you confirm if amazon provider is supported for Spinnaker operator pubsub configuration?
