### ISSUE TITLE
There is no `cluster ` folder under `deploy/spinnaker`

### ISSUE THREAD

**Issue by dervistalha** [armory/spinnaker-operator#175]
Hello;

 `bash -c 'curl -L https://github.com/armory-io/spinnaker-operator/releases/latest/download/manifests.tgz | tar -xz'`

documentations says;
`kubectl -n spinnaker-operator apply -f deploy/spinnaker/cluster/SpinnakerService.yml`

There is no `cluster ` folder under `deploy/spinnaker`

Thanks

**Comment by sh4sh** [comment]
Thanks for the report! Docs were fixed in https://github.com/armory/docs/issues/326:

> that filepath is supposed to be deploy/spinnaker/kustomize/SpinnakerService.yml.
> 
> So the full command is:
> kubectl -n spinnaker-operator apply -f deploy/spinnaker/kustomize/SpinnakerService.yml
