### ISSUE TITLE
Spin CLI not working with authorization enabled

### ISSUE THREAD

**Issue by Anta-Krumina** [armory/spinnaker-operator#202]
When trying to save application with command:
`spin application save --owner-email email@email.com --cloud-providers kubernetes --insecure=true --application-name application`

It throws the error message as follows:

```
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/spinnaker/spin/cmd/orca-tasks.idFromTaskRef(0x0, 0x0, 0x0)
        /var/lib/jenkins/workspace/Build_PrimaryArtifacts/build_input/build_spin/spin/cmd/orca-tasks/task_watcher.go:80 +0xf7
github.com/spinnaker/spin/cmd/orca-tasks.WaitForSuccessfulTask(0xc000109b90, 0x0, 0x5, 0x97d4a0, 0xc00015aab0)
        /var/lib/jenkins/workspace/Build_PrimaryArtifacts/build_input/build_spin/spin/cmd/orca-tasks/task_watcher.go:27 +0x40
github.com/spinnaker/spin/cmd/application.saveApplication(0xc000119b80, 0xc000076840, 0x0, 0x0)
        /var/lib/jenkins/workspace/Build_PrimaryArtifacts/build_input/build_spin/spin/cmd/application/save.go:111 +0x510
github.com/spinnaker/spin/cmd/application.NewSaveCmd.func1(0xc000119b80, 0xc000109b20, 0x0, 0x7, 0x0, 0x0)
        /var/lib/jenkins/workspace/Build_PrimaryArtifacts/build_input/build_spin/spin/cmd/application/save.go:50 +0x34
github.com/spf13/cobra.(*Command).execute(0xc000119b80, 0xc000109ab0, 0x7, 0x7, 0xc000119b80, 0xc000109ab0)
        /var/lib/jenkins/workspace/Build_PrimaryArtifacts/build_input/build_spin/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000118780, 0xc0000a29c0, 0xb049e0, 0xc0000a0010)
        /var/lib/jenkins/workspace/Build_PrimaryArtifacts/build_input/build_spin/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /var/lib/jenkins/workspace/Build_PrimaryArtifacts/build_input/build_spin/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /var/lib/jenkins/workspace/Build_PrimaryArtifacts/build_input/build_spin/spin/main.go:29 +0x7e
```

- Spin CLI version: 1.20.0

- Spin cli config file:

```
gate:
  endpoint: <our endpoint>
auth:
  enabled: true
  basic:
    username: <username>
    password: <password>
```

- Spinnaker operator manifest is attached.
[SpinnakerService.txt](https://github.com/armory/spinnaker-operator/files/5710686/SpinnakerService.txt)

As a temporary workaround we are disabling authorization to use spin CLI, but looking for a solution with authorization enabled.

**Comment by jasonmcintosh** [comment]
This kinda thing isn't actually operator, but more likely, an issue with either the spin cli or spinnaker itself.  Looking at the error I'd guess a mismatch to what's running in spinnaker from your CLI.  https://github.com/spinnaker/spinnaker/issues is probably a better location for these, but generally "help" type requests aren't the province of issues, but instead use slack.  See https://spinnaker.io/community/#engage-the-community-and-get-support

BUT a quick glance at your manifest.. things seem odd.  E.g. you have UI/API security disabled, oauth enabled, which is not compatible with basic auth.

**Comment by dogonthehorizon** [comment]
Going to close this issue as it appears related to the spin-cli. If we're seeing issues with the Operator please do re-open or file a new issue!
