### ISSUE TITLE
Install issue - Google bucket as storage 

### ISSUE THREAD

**Issue by szubair** [armory/spinnaker-operator#206]
Hi all - I have tried to install spinnaker using spinnaker-operator and GCS bucket as storage. Unfortunate, I see spin-front50 and spin-echo pods are not running. Please help me resolve this issue.  

$ cat spinnakerservice.yml
---cut---
    config:
      version: 1.17.1   # the version of Spinnaker to be deployed
      persistentStorage:
        persistentStoreType: gcs
        gcs:
          project: xxxxxxxxxx0256073
          bucket: spin-pov # Change to a unique name. Spinnaker stores application and pipeline definitions here
          rootFolder: front50
---cut---

**Comment by szubair** [comment]
Hi - I am able to resolve this issue. 
Added GCP service key in the secrets and then added as jsonPath. 
---cut---
persistentStorage:
persistentStoreType: gcs
gcs:
project: xxxxxxxxxx0256073
bucket: spin-pov # Change to a unique name. Spinnaker stores application and pipeline definitions here
rootFolder: front50
jsonPath: encryptedFile:k8s!n:gcs-account!k:gcs-account.json
---cut---

**Comment by ysde** [comment]
Hi @szubair 

Can you help explain this line ?

`jsonPath: encryptedFile:k8s!n:gcs-account!k:gcs-account.json`

Does it mean I need to create a `gcs-account` and download it's key file `gcd-account.json`, then put this file in somewhere?

Many thanks
