### ISSUE TITLE
Many echo secrets created

### ISSUE THREAD

**Issue by ncknt** [armory/spinnaker-operator#215]
Every time the operator runs through reconciliation a new Echo secret is created. The end result is a lot of echo secrets and Echo being updated for every change to `SpinnakerService`.

It appears to be linked to the statistics reporting that generates a new ULID at every loop. A workaround might be to set a fixed instanceID (`spec.spinnakerConfig.config.stats.instanceId: xxxxx`).

Ideally, the operator would generate the instanceID and store it in `status` and pass that value to the Echo.

**Comment by camechis** [comment]
I had this issue as well. I had 160K secrets generated in the cluster.  I was able to make it work by setting the instanceID as suggested above.

**Comment by dogonthehorizon** [comment]
We believe this is resolved in the latest version of the Operator, lets do please re-open or file a new issue if this persists in the latest version (1.3.x at the time of this writing)
