### ISSUE TITLE
Spinnaker pipelineTemplates not enabled

### ISSUE THREAD

**Issue by Lord-Y** [armory/spinnaker-operator#230]
Hello guys,

I'm testing spinnaker armory operator and so far, everything is working execpt `spec.spinnakerConfig.config.features` cf documentation here: https://docs.armory.io/docs/installation/armory-operator/op-manifest-reference/features/

My config is as simple as below:

```
spinnakerService:
  enabled: true
  spinnakerConfig:
    ...
    ...
    config:
      ...
      ...
      features:
        chaos: false
        pipelineTemplates: true
```

Any ideas what's wrong as I don't see any errors in logs?
I'm using chart/docker image 1.2.5

**Comment by sh4sh** [comment]
Hey @Lord-Y, that config looks good. Now you also need to enable it in `settings-local.js` to have it show up in the UI:

```
apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      features:
        pipelineTemplates: true
    profiles:
      deck:
        settings-local.js: |
          window.spinnakerSettings.feature.pipelineTemplates = true;
          window.spinnakerSettings.feature.managedPipelineTemplatesV2UI = true;
```

**Comment by Lord-Y** [comment]
@sh4sh I upgraded to version 1.2.7 and I can confirm that the issue is solved. thx.
