### ISSUE TITLE
Support to adjust readiness probe to use HTTPS scheme instead of wget 

### ISSUE THREAD

**Issue by zvazquez** [armory/spinnaker-operator#231]
Hi all,

We are experiencing a problem mentioned in [here](https://github.com/spinnaker/halyard/pull/1343) where there are considerable amount of zombie process left at the host OS, by example:

10111    32555  0.0  0.0      0     0 ?        Z    20:17   0:00 [ssl_client] <defunct>
10111    32557  0.0  0.0      0     0 ?        Z    17:52   0:00 [ssl_client] <defunct>
10111    32563  0.0  0.0      0     0 ?        Z    20:37   0:00 [ssl_client] <defunct>
10111    32578  0.0  0.0      0     0 ?        Z    17:52   0:00 [ssl_client] <defunct>
10111    32586  0.0  0.0      0     0 ?        Z    20:17   0:00 [ssl_client] <defunct>
10111    32588  0.0  0.0      0     0 ?        Z    20:37   0:00 [ssl_client] <defunct>
10111    32612  0.0  0.0      0     0 ?        Z    18:07   0:00 [ssl_client] <defunct>
10111    32652  0.0  0.0      0     0 ?        Z    18:22   0:00 [ssl_client] <defunct>
10111    32660  0.0  0.0      0     0 ?        Z    18:45   0:00 [ssl_client] <defunct>
10111    32690  0.0  0.0      0     0 ?        Z    19:43   0:00 [ssl_client] <defunct>

As you can imagine, with this behavior the node where this pods are running eventually become unresponsive affecting Spinnaker and all other application running on the same node.

As it is mentioned in different threads, the recommendation is to change the readinessProbe to use httpGet instead of the wget command, but I could not find a way to achieve this change using the operator.

**If you can point me to the documentation or the configuration required to change the readinessProbe to use httpGet intead of the exec.command, which is supported by Spinnaker based on [PR 1344](https://github.com/spinnaker/halyard/pull/1344) .**

Thanks,

Zareh

**Comment by sh4sh** [comment]
You can enable `httpGet` and disable `wget` health checks by setting `kubernetes.useExecHealthCheck : false` for each service in the `service-settings` config section. More info here: https://spinnaker.io/reference/halyard/custom/#useexechealthcheck

Enabling for Clouddriver and Orca would look something like this, but you can configure this for any Spinnaker service:

```
spec:
  spinnakerConfig:
    config:
    ...
    service-settings:
      clouddriver:
        kubernetes:
          useExecHealthCheck: false
      orca:
        kubernetes:
          useExecHealthCheck: false
```
More detail on configuring service settings with Operator in this doc: https://docs.armory.io/docs/installation/armory-operator/op-config-manifest/#specspinnakerconfigservice-settings

**Comment by dogonthehorizon** [comment]
@zvazquez going to close this issue due to inactivity. If you're still facing issues w/ healthchecks please do reopen the issue or create a new one for us to take a look!
