### ISSUE TITLE
Number of items (1290) to cache exceeds upper threshold (1000) in monitor=DockerMonitor partition=my-ecr-registry

### ISSUE THREAD

**Issue by Asshad** [armory/spinnaker-operator#239]
Hi. Facing this issue, which our ECR registry can't trigger the deployment, and list down of the ECR, missing the latest push tag.

Digging further, found this solution to increase the itemUpperThreshold in igor profile. 

Related link:
https://github.com/spinnaker/spinnaker/issues/2873

My question is, how can I do that in spinnaker operator?

Thanks in advance.

**Comment by jasonmcintosh** [comment]
https://docs.armory.io/docs/installation/operator-reference/ docs for configuration of an operator.  This particular one would be in a profiles section for igor to adjust the settings.  https://docs.armory.io/docs/installation/armory-operator/op-config-manifest/#specspinnakerconfigprofiles

**Comment by dogonthehorizon** [comment]
@Asshad are you still facing this issue? If so would be great to get more details on your setup!

**Comment by dogonthehorizon** [comment]
Going to close this issue for now, if we're still seeing this behavior please do re-open or file a new issue!
