### ISSUE TITLE
Bump CRD Versions to v1

### ISSUE THREAD

**Issue by danehans** [armory/spinnaker-operator#241]
The [current CRD versions](https://github.com/armory/spinnaker-operator/tree/master/deploy/crds), i.e. `apiextensions.k8s.io/v1beta1` are deprecated since k8s v.16 and will be unavailable in 1.22+. The versions will need to be bumped to use the operator with the upcoming k8s release.

**Comment by dogonthehorizon** [comment]
Hi @danehans thanks for the report, the card referenced by @aryabchenko has been resolved and the latest version of the Operator (1.3.0 at time of writing) works with k8s 1.22+. Please feel free to reopen if we need to look at this further
