### ISSUE TITLE
spinnaker-operator container has wrong dns behavior due to old go version.

### ISSUE THREAD

**Issue by fredwangwang** [armory/spinnaker-operator#249]
See: https://github.com/golang/go/issues/35305

## Context:
In a system with search domain configured, and there is a machine wrongly configured to have hostname as `localhost`, then in the old version of go with alpine base image it will resolve localhost to the other machine's ip instead of `127.0.0.1`.

I dont have the exact logs any more, but essentially here is what looks like:

![image](https://user-images.githubusercontent.com/21690857/145248585-e2e4e4da-45a9-48d5-b32f-ad3d5625b041.png)

## Fix:

Either bump the golang image for compilation to 1.15 (I believe some patch version of 1.14 has the fix as well, but 1.15 for sure) or above,
Or add `RUN [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' > /etc/nsswitch.conf` into the dockerfile for the final stage.

**Comment by dogonthehorizon** [comment]
@fredwangwang thanks for the issue, the most recent release of the Spinnaker Operator (1.3.0 at time of writing) is using golang 1.18 and believe this to be resolved. Please re-open if we're still seeing this behavior and we'll take another look!
