### ISSUE TITLE
Mergify: strict mode deprecated

### ISSUE THREAD

**Issue by Eugst** [armory/spinnaker-operator#253]
https://blog.mergify.com/strict-mode-deprecation/ strict mode was deprecated.
mergify config need to be refactored.

**Comment by Eugst** [comment]
#254

**Comment by dogonthehorizon** [comment]
@Eugst it looks like we have resolved this in another commit that exists on master. Thank you for the contribution, but I'll go ahead and close this (and the related PR) for now unless we need further changes made to the mergify config!
