### ISSUE TITLE
Operator have validation error in k8s 1.22

### ISSUE THREAD

**Issue by DodgeCamaro** [armory/spinnaker-operator#274]
spinnaker-operator:1.3.0-rc.21 have errors 
Error from server (InternalError): error when creating "spin.yml": Internal error occurred: failed calling webhook "webhook-spinnakerservices-v1alpha2.spinnaker.io": failed to call webhook: Post "https://spinnaker-operator.spinnaker.svc:443/validate-spinnaker-io-v1alpha2-spinnakerservice?timeout=10s": context deadline exceeded

spinnaker-operator:1.2.5 have errors 
{"level":"error","ts":1663320321.5542288,"logger":"cmd","msg":"error starting webhook server","error":"the server could not find the requested resource","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/opt/spinnaker-operator/build/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/armory/spinnaker-operator/pkg/operator.Start\n\t/opt/spinnaker-operator/build/pkg/operator/operator.go:138\nmain.main\n\t/opt/spinnaker-operator/build/cmd/manager/main.go:24\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}

**Comment by wangycc** [comment]
No support for k8s 1.22+? no one is handling it?

**Comment by LukasdeBoer** [comment]
Any progress here? EKS 1.21 is EOL on february 15th 2023 and Spinnaker not supporting 1.22 is a big problem when clusters are gonna be auto upgraded.

**Comment by christosarvanitis** [comment]
Workaround for the above issue: 
- Delete the validation webhook
```
kubectl delete ValidatingWebhookConfiguration spinnakervalidatingwebhook 
```
- Deploy the operator with disabled the admission-controller
```
...
          command:
           - spinnaker-operator
           args:
           - --disable-admission-controller
...
```

**Comment by brian-provenzano** [comment]
We have the same issue trying to move to 1.22

What impact does this have on functionality?  What does this webhook validate exactly?

**Comment by christosarvanitis** [comment]
Disabling the admission-controller basically disabled the spinnakerservice custom resource validation against the CRD schema before applying it.
So for example if you deploy a spinnakerservice manifest which doesnt follow the CRD schema the validation webhook will throw you an error before it applies it. Without the validationwebhook the manifest will be applied but then spinnaker-operator will throw errors for unknown properties etc

**Comment by brian-provenzano** [comment]
OK - so for clarification this is only for spinnaker related CRDs?

**Comment by GenPage** [comment]
Yes, any webhooks setup by the spinnaker-operator validate only Spinnaker CRDs created by the operator.

**Comment by KshitijaR16** [comment]
Hi team,

Even we are facing issue for spinnaker-operator, with same error as mentioned above.
@brian-provenzano is delete webhook and disable admission controller worked for you

**Comment by sergio-quintero** [comment]
[Lates Operator 1.3.0 release](https://github.com/armory/spinnaker-operator/releases/tag/v1.3.0) has added support for K8s 1.22+. 

[K8s Compatibility Matrix](https://github.com/armory/spinnaker-operator#kubernetes-compatibility-matrix)

**Comment by brian-provenzano** [comment]
> Hi team,
> 
> Even we are facing issue for spinnaker-operator, with same error as mentioned above. @brian-provenzano is delete webhook and disable admission controller worked for you

sorry, late on this, but "yes" it did
