### ISSUE TITLE
new github release

### ISSUE THREAD

**Issue by dmichel1** [armory/spinnaker-operator#275]
Hello there,

I see docker images being published up to version `1.3.0-rc.21` but no github releases since 1.2.5. Would it be possible to get a new github release with a diff of all the changes?

Thanks

**Comment by puneetsingh23** [comment]
current spinnaker release does not support k8 1.22+, Any plant to merge v1.3.0-rc.21 and create new release

**Comment by ovidiupopa07** [comment]
hi @dmichel1 / @puneetsingh23  -  release 1.3.0 is available since yesterday. I will close this issue now
